/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.khiem.offsite.backup.schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Box extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Box\",\"namespace\":\"de.khiem.offsite.backup.schema\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"owner\",\"type\":{\"type\":\"record\",\"name\":\"BoxUser\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public de.khiem.offsite.backup.schema.BoxUser owner;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Box() {}

  /**
   * All-args constructor.
   */
  public Box(java.lang.CharSequence name, java.lang.CharSequence id, de.khiem.offsite.backup.schema.BoxUser owner) {
    this.name = name;
    this.id = id;
    this.owner = owner;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return owner;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    case 2: owner = (de.khiem.offsite.backup.schema.BoxUser)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'owner' field.
   */
  public de.khiem.offsite.backup.schema.BoxUser getOwner() {
    return owner;
  }

  /**
   * Sets the value of the 'owner' field.
   * @param value the value to set.
   */
  public void setOwner(de.khiem.offsite.backup.schema.BoxUser value) {
    this.owner = value;
  }

  /** Creates a new Box RecordBuilder */
  public static de.khiem.offsite.backup.schema.Box.Builder newBuilder() {
    return new de.khiem.offsite.backup.schema.Box.Builder();
  }
  
  /** Creates a new Box RecordBuilder by copying an existing Builder */
  public static de.khiem.offsite.backup.schema.Box.Builder newBuilder(de.khiem.offsite.backup.schema.Box.Builder other) {
    return new de.khiem.offsite.backup.schema.Box.Builder(other);
  }
  
  /** Creates a new Box RecordBuilder by copying an existing Box instance */
  public static de.khiem.offsite.backup.schema.Box.Builder newBuilder(de.khiem.offsite.backup.schema.Box other) {
    return new de.khiem.offsite.backup.schema.Box.Builder(other);
  }
  
  /**
   * RecordBuilder for Box instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Box>
    implements org.apache.avro.data.RecordBuilder<Box> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence id;
    private de.khiem.offsite.backup.schema.BoxUser owner;

    /** Creates a new Builder */
    private Builder() {
      super(de.khiem.offsite.backup.schema.Box.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.khiem.offsite.backup.schema.Box.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.owner)) {
        this.owner = data().deepCopy(fields()[2].schema(), other.owner);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Box instance */
    private Builder(de.khiem.offsite.backup.schema.Box other) {
            super(de.khiem.offsite.backup.schema.Box.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.owner)) {
        this.owner = data().deepCopy(fields()[2].schema(), other.owner);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public de.khiem.offsite.backup.schema.Box.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public de.khiem.offsite.backup.schema.Box.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public de.khiem.offsite.backup.schema.Box.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public de.khiem.offsite.backup.schema.Box.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'owner' field */
    public de.khiem.offsite.backup.schema.BoxUser getOwner() {
      return owner;
    }
    
    /** Sets the value of the 'owner' field */
    public de.khiem.offsite.backup.schema.Box.Builder setOwner(de.khiem.offsite.backup.schema.BoxUser value) {
      validate(fields()[2], value);
      this.owner = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'owner' field has been set */
    public boolean hasOwner() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'owner' field */
    public de.khiem.offsite.backup.schema.Box.Builder clearOwner() {
      owner = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public Box build() {
      try {
        Box record = new Box();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.owner = fieldSetFlags()[2] ? this.owner : (de.khiem.offsite.backup.schema.BoxUser) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
