/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package de.khiem.offsite.backup.schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BoxUser extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BoxUser\",\"namespace\":\"de.khiem.offsite.backup.schema\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public BoxUser() {}

  /**
   * All-args constructor.
   */
  public BoxUser(java.lang.CharSequence name, java.lang.CharSequence id) {
    this.name = name;
    this.id = id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /** Creates a new BoxUser RecordBuilder */
  public static de.khiem.offsite.backup.schema.BoxUser.Builder newBuilder() {
    return new de.khiem.offsite.backup.schema.BoxUser.Builder();
  }
  
  /** Creates a new BoxUser RecordBuilder by copying an existing Builder */
  public static de.khiem.offsite.backup.schema.BoxUser.Builder newBuilder(de.khiem.offsite.backup.schema.BoxUser.Builder other) {
    return new de.khiem.offsite.backup.schema.BoxUser.Builder(other);
  }
  
  /** Creates a new BoxUser RecordBuilder by copying an existing BoxUser instance */
  public static de.khiem.offsite.backup.schema.BoxUser.Builder newBuilder(de.khiem.offsite.backup.schema.BoxUser other) {
    return new de.khiem.offsite.backup.schema.BoxUser.Builder(other);
  }
  
  /**
   * RecordBuilder for BoxUser instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BoxUser>
    implements org.apache.avro.data.RecordBuilder<BoxUser> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence id;

    /** Creates a new Builder */
    private Builder() {
      super(de.khiem.offsite.backup.schema.BoxUser.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(de.khiem.offsite.backup.schema.BoxUser.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing BoxUser instance */
    private Builder(de.khiem.offsite.backup.schema.BoxUser other) {
            super(de.khiem.offsite.backup.schema.BoxUser.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public de.khiem.offsite.backup.schema.BoxUser.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public de.khiem.offsite.backup.schema.BoxUser.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'id' field */
    public java.lang.CharSequence getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public de.khiem.offsite.backup.schema.BoxUser.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'id' field */
    public de.khiem.offsite.backup.schema.BoxUser.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public BoxUser build() {
      try {
        BoxUser record = new BoxUser();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
